version: '3.4'

services:
  Movie.Login.API:
    image: ${DOCKER_REGISTRY-}Movie.Login.API
    container_name: apiaspn
    build:
      context: .
      dockerfile: Movie.Login.API/Dockerfile
    depends_on: 
      - database
    ports:
      - "5000:80"
    restart: always
    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development
       
  database:
    image: mysql:8.0.22
    container_name: mysqldbr
    ports:
      - "3307:3306"
    expose: 
      - 3306
    volumes:
      - db-volume:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: filt
      MYSQL_USER: mac
      MYSQL_PASSWORD: filt
      MYSQL_DATABASE: MovieAPiProjectDb

volumes:
  db-volume: